name: s3-depl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: npm ci
      - name: Build Gatsby App
        run: npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./public/ s3://www.bobderrico.com --delete
      # - name: Invalidate index.html on CloudFront
      #   run: aws cloudfront create-invalidation --distribution-id EDFFBQN7WWVGQ --paths /index.html
